### ISSUE TITLE
BUG: manta crashes getting information for git clusters

### ISSUE THREAD

**Issue by Masber** [eth-cscs/manta#76]
eg `manta get cluster santis` will break

```
thread 'tokio-runtime-worker' panicked at /home/msopena/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mesa-0.37.5/src/cfs/component/mesa/http_client.rs:84:14:
called `Result::unwrap()` on an `Err` value: CsmError(Object {"detail": String("The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."), "status": Number(500), "title": String("Internal Server Error"), "type": String("about:blank")})
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at /home/msopena/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mesa-0.37.5/src/cfs/component/mesa/http_client.rs:84:14:
called `Result::unwrap()` on an `Err` value: CsmError(Object {"detail": String("The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."), "status": Number(500), "title": String("Internal Server Error"), "type": String("about:blank")})
```

The error relates to CFS component API to fetch desired configuration for a group of nodes. For some reason CSM can't cope with the load, even knowing we are processing multiple requests (each with 30 nodes) sequentially.

**Comment by Masber** [comment]
solved in new mesa version v1.36.3
